$ANSIBLE_VAULT;1.1;AES256
37323861393937376138353063363936653937323033346134393263353064313461386337323863
3732633339633339363833316265356461323134333836330a356161623931613532623234326161
62623734313465643635316638346134386335313534363065333233663239303162363932333033
3837313361326565640a306261336633306539653030386133666435643262303035373733313038
61343233393636343235326264613437353363346431393233386230666131353561643537343766
63313038393165643336363864306562333162353435346636663566326463336163373634663164
66616433376339666230376564356264626336386430626630366266656464373561306132623462
31393163356539303934353366383034366131383761333939646365646439386531393739313836
33323631633663326364326166613438343230393338666562633963643138316265313662616463
31626461636236333635333466373938343961333961623436326332343365663134393434323463
32653231393233636235326235383166373930383865643562383034613861626237303963333961
64623331333863333962353539353633613038666662303636313431313564396130393636346630
63626261663235376437383534393132346439623034383436306663326338303434303564333835
63303066636266623136353931333066353665393138323136346562313462626662363334623966
61633137666662326335363363333661613334616235396531383236373138333832376239376132
64623835383161656532393663326430303431326463613937373339333130636230333535646464
63393139353665303230663532633237386435636439666231373039386265613837366533636637
64623036323635653931633531643930393533663761616565346430373462643437353035623332
32653562633439336130326336623934353939333831666538383731303437383263653033323737
61636331353162303266383037653537656662353638613462386131303638323036626435396439
61633463626135356532356266336235643162333937373164323837633633646561613935386538
62383632346266613439316465326132323735363062646335363439613233326535626635393164
32616263643130373563396231336637373662373638303431363936343039306238393761646534
35323031303933313561373830313466353237653034636265363333376266383038633034323936
65383137663838636338396366653136303734366334323438366437656163363332373230353937
36376235636663396163653262313337656530633336316364643834303439386139633538393338
36616133313432353062613833366135633232383564646666643562656138316531616634343061
30616439323430373531
